spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 9292
  error:
    include-message: always
    include-binding-errors: always
#    include-stacktrace: always
    include-exception: false

